package models

// MedicalSpecialties contains a comprehensive list of medical specialties
var MedicalSpecialties = []string{
	"Allergy and Immunology",
	"Anesthesiology",
	"Cardiology",
	"Cardiothoracic Surgery",
	"Critical Care Medicine",
	"Dermatology",
	"Emergency Medicine",
	"Endocrinology",
	"Family Medicine",
	"Gastroenterology",
	"General Surgery",
	"Geriatrics",
	"Hematology",
	"Infectious Disease",
	"Internal Medicine",
	"Medical Genetics",
	"Nephrology",
	"Neurology",
	"Neurosurgery",
	"Nuclear Medicine",
	"Obstetrics and Gynecology",
	"Oncology",
	"Ophthalmology",
	"Orthopedic Surgery",
	"Orthopedics",
	"Otolaryngology (ENT)",
	"Pathology",
	"Pediatrics",
	"Physical Medicine and Rehabilitation",
	"Plastic Surgery",
	"Psychiatry",
	"Pulmonology",
	"Radiation Oncology",
	"Radiology",
	"Rheumatology",
	"Sports Medicine",
	"Thoracic Surgery",
	"Urology",
	"Vascular Surgery",
}

